# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cresh' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cresh
    pod 'Parse'
    pod 'Parse/UI'
    pod 'AlamofireImage'
    pod 'AFNetworking'
    pod 'Charts'

  target 'CreshTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CreshUITests' do
    # Pods for testing
  end

end
